name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Try install
        run: ./install-headless.sh
